markdown: rdiscount 
permalink: /:year/:month/:day/:title 
title: Liang
url: http://liangshilei.com
subscribe: http://ztpala.com/feed.xml
exclude: [ README.md, newpost.rb ]
domain: liangshilei.com
author: Liang Shilei
email: xmuliang@gmail.com
auto: true
disqusShortname: Liang
